[package]
name = "gustav"
version = "0.1.0"
edition = "2021"
description = "An automated job orchestration library to build and execute dynamic workflows"

[dependencies]
json-patch = "3"
jsonptr = "0.6.0"
matchit = "0.8.4"
serde = { version = "1.0.197" }
serde_json = "1.0.120"
thiserror = "2"

[dev-dependencies]
dedent = "0.1.1"
tokio = { version = "1.36.0", features = ["rt", "macros", "time"] }
