[package]
name = "gustav"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
json-patch = "2.0.0"
serde = { version = "1.0.197" }
serde_json = "1.0.120"
thiserror = "1.0.63"

[dev-dependencies]
tokio = { version = "1.36.0", features = ["rt", "macros"] }
