[package]
name = "gustav"
version = "0.10.0"
edition = "2021"
description = "An automated job orchestration library to build and execute dynamic workflows"

[features]

default = []
logging = ["tracing-subscriber", "log"]

[dependencies]
anyhow = "1.0.97"
json-patch = "4"
jsonptr = "0.7.1"
matchit = "0.8.4"
serde = { version = "1.0.197" }
serde_json = "1.0.120"
thiserror = "2"
tokio = { version = "1.43.0", default-features = false, features = [
  "rt",
  "time",
  "sync",
  "macros",
] }
tracing = "0.1.41"
tokio-stream = { version = "0.1.17", features = ["sync"] }
async-trait = "0.1.88"

# only required by the `logging` feature
log = { version = "0.4.25", optional = true }
tracing-subscriber = { version = "0.3.19", default-features = false, optional = true, features = [
  "registry",
] }
futures = "0.3.31"

[dev-dependencies]
tracing-subscriber = { version = "0.3.19", default-features = false, features = [
  "ansi",
  "registry",
  "fmt",
  "env-filter",
] }
dedent = "0.1.1"
env_logger = "0.11.8"
log = "0.4.25"
tokio = { version = "1.36.0", features = ["rt", "macros", "time"] }
pretty_assertions = "1.4.1"
